export const environment = {
  production: true,
  adtenantid: (window as any)?.envConfig?.adtenantid,
  adclientid: (window as any)?.envConfig?.adclientid,
  languages: ['ro', 'en'],
  defaultLanguage: 'ro',
  publicvapidkey: (window as any)?.envConfig?.publicvapidkey,
  notificationsElementsPerPage: 50,
  toastDuration: 5000,
  acceptedFileExtensions: [
    '.zip',
    '.rar',
    '.7z',
    '.cab',
    '.png',
    '.jpg',
    '.jpeg',
    '.gif',
    '.mp4',
    '.avi',
    '.mkv',
    '.mp3',
    '.wav',
    '.pdf',
    '.xls',
    '.xlsx',
    '.ppt',
    '.pptx',
    '.doc',
    '.docx',
    '.accdb',
    '.sql',
    '.rtf',
    '.txt',
    '.tar',
    '.gz',
    '.bz2'
  ]
};
