name: qeeps-ui
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v2.3.0
        with:
          node-version: '16.x'

      - name: cache node_modules
        uses: actions/cache@v2
        id: cache-nodemodules
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: npm install
        run: npm ci

      - name: npm build
        run: npm run build

      - name: upload artifact
        uses: actions/upload-artifact@v2.2.4
        if: ${{ success() && github.event_name != 'pull_request' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') }}
        with:
          name: dist
          path: ./dist/qeeps-ui

  deploy_stg:
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    needs: [build]
    environment: stg
    env:
      adclientid: '${{ secrets.adclientid }}'
      adtenantid: '${{ secrets.adtenantid }}'
    name: deploy stg
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: 'dist'
          path: ./dist

      - name: replace secrets
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["./dist/index.html"]'

      - name: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'dist'
          api_location: 'api'
          output_location: ''
          skip_app_build: true

  deploy_prod:
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: [build]
    environment: prod
    env:
      adclientid: '${{ secrets.adclientid }}'
      adtenantid: '${{ secrets.adtenantid }}'
    name: deploy prod
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: 'dist'
          path: ./dist


      - name: replace secrets
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["./dist/index.html"]'

      - name: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'dist'
          api_location: 'api'
          output_location: ''
          skip_app_build: true
